config/routes.rb
Rails.application.routes.draw do
  resources :tracks do
    resources :courses
  end

  resources :courses do
    resources :lessons
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :track
  validates :name, :presence => true
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :course
  validates :name, :presence => true
end

app/models/track.rb
class Track < ActiveRecord::Base
  has_many :courses
  validates :name, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def new
    @track = Track.find(params[:track_id])
    @course = @track.courses.new
  end

  def show
    @track = Track.find(params[:track_id])
    @course = Course.find(params[:id])
  redirect_to tracks_path(@course)
end

  def create
    @track = Track.find(params[:track_id])
    @course = @track.courses.new(course_params)
    if @course.save
      redirect_to track_path(@course.track)
    else
      render :new
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to tracks_path(@course.track)
  end

  def edit
    @track = Track.find(params[:track_id])
    @course = Course.find(params[:id])
  end

  def update
  @track = Track.find(params[:track_id])
  @course = Course.find(params[:id])
  if @course.update(course_params)
    redirect_to track_course_path
  else
  render :edit
  end
end

private
  def course_params
    params.require(:course).permit(:name)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def new
    @lesson = Course.find(params[:lesson_id])
    @course = @lesson.courses.new
  end

  def show
    @lesson = Course.find(params[:lesson_id])
    @course = Lesson.find(params[:id])
  redirect_to lessons_path(@course)
end

  def create
    @lesson = Course.find(params[:lesson_id])
    @course = @lesson.courses.new(course_params)
    if @course.save
      redirect_to lesson_path(@course.lesson)
    else
      render :new
    end
  end


private
  def lesson_params
    params.require(:lesson).permit(:name)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    @tracks = Track.all
    render :index
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def new
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to tracks_path
    else
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to tracks_path
    else
      render :edit
    end
  end

  def destroy
  @track = Track.find(params[:id])
  @track.destroy
  redirect_to tracks_path
end


  private
    def track_params
      params.require(:track).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.erb
<%= render('layouts/errors', :object => @course) %>

<%= form_for [@track, @course] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/courses/edit.html.erb
<h1>New course for <%= @course.name %></h1>

<%= render 'form' %>

app/views/courses/new.html.erb
<h1>New course for <%= @track.name %></h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if @track.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% @track.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/_form.html.erb
<%= render('layouts/errors', :object => @course) %>

<%= form_for [@track, @course] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <title>RebuildEpicodus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-light">
    <a href="https://www.learnhowtoprogram.com/tracks" class="navbar-brand">Tracks</a>
    <form class="form-inline">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-info my-2 my-sm-0" type="submit">Search</button>
    </form>
  </nav>

    <div class="container">
      <div id="mainbody">
        <%= yield %>
      </div>
      <div class="bottom-footer">
        <img id="epicodusLogo" src="https://static1.squarespace.com/static/5524448ee4b0d6f6b83ab9e2/t/57cf3de246c3c4d2933aa57c/1529949737992/?format=1500w" alt="epicodus logo">
        <p>© 2018 <a href="https://www.learnhowtoprogram.com/tracks">Epicodus</a> , Inc.</p>
      </div>
    </div>
  </body>
</html>

app/views/lesson/index.html.erb
<h1>Lessons</h1>

<ul>
  <% @lessons.each do |lesson| %>
    <p><%= link_to lesson.name, lesson_path(lesson) %></p>
  <% end %>
</ul>

<hr>

<%= link_to "New Lesson", new_lesson_path %>

app/views/lesson/show.html.erb
<h1><%= @course.name %></h1>

<% if @course.lessons.any? %>
  <h4>Here are the lessons for this course:</h4>

  <ol>
    <% @course.lessons.each do |lesson| %>
      <li>
      <a href="#">  <%= lesson.name %> </a>|
        <%= link_to "Edit", edit_course_lesson_path(@course, lesson) %> |
        <%= link_to "Delete", course_lesson_path(@course, lesson),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ol>
<% else %>
  <p>There are no lessons yet!</p>
<% end %>

<p><%= link_to "Add a lesson", new_course_lesson_path(@course) %></p>
<p><%= link_to "Delete List", course_path(@course),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to courses", courses_path %></p>

app/views/tracks/edit.html.erb
<h1>Edit Track Name</h1>

<% if @track.errors.any? %>
<h3>Please fix these errors:</h3>

<ul>
  <% @track.errors.full_message.each do |message| %>
  <% end %>
</p>
<% end %>

<%= form_for @track do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/tracks/index.html.erb
<h1>Tracks</h1>

<ul>
  <% @tracks.each do |track| %>
    <p><%= link_to track.name, track_path(track) %></p>
  <% end %>
</ul>

<hr>

<%= link_to "New Track", new_track_path %>

app/views/tracks/new.html.erb
<h1>New track</h1>

<% if @track.errors.any? %>
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% @track.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @track do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>

<% if @track.courses.any? %>
  <h4>Here are the courses for this track:</h4>

  <ol>
    <% @track.courses.each do |course| %>
      <li>
      <a href="/courses/<%= course.id %>/lessons/">  <%= course.name %> </a>|
        <%= link_to "Edit", edit_track_course_path(@track, course) %> |
        <%= link_to "Delete", track_course_path(@track, course),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ol>
<% else %>
  <p>There are no courses yet!</p>
<% end %>

<p><%= link_to "Add a course", new_track_course_path(@track) %></p>
<p><%= link_to "Delete List", track_path(@track),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to tracks", tracks_path %></p>